### ISSUE TITLE
Email doesn't sync with pterodactyl after updating

### ISSUE THREAD

**Issue by ayodev-in** [ControlPanel-gg/dashboard#231] opened 2021-10-16 03:30 UTC
**Describe the bug 🐛**
When a user change its email it does not change on panel but changes on dashboard for some reason

**Comment by anondev-sudo** [comment] 2021-10-16 06:27
I know that, also when you change password on dashboard it's not changed on panel.
I think that there should be config option to change email and password on pterodactyl too when it's changed on dashboard (or when password is reset on dashboard)

**Comment by BitSec01** [comment] 2021-10-16 15:55
Should be possible with the Pterodactyl Api: https://dashflo.net/docs/api/pterodactyl/v1/#req_677bed2d8281425ab9e428fa6ed292e5

**Comment by anondev-sudo** [comment] 2021-10-16 16:03
Yes you can update user on pterodactyl using API

**Comment by AVMG20** [comment] 2021-10-20 06:19
Please, next time, make sure the title of the issue is more precise. This title is very confusing.

**Comment by 1day2die** [comment] 2021-12-27 07:41
Will be fixed by https://github.com/ControlPanel-gg/dashboard/pull/348

**Closed by 1day2die** 2021-12-27 07:41 UTC
Labels: bug, Low Priority
