### ISSUE TITLE
[feature] Webhook notifications for tickets

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#513] opened 2022-08-10 09:05 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

Kind of. I (and my support members) always have to look at the tickets page a few times a day to check if there's a new ticket. 

### Describe the solution you'd like

It would be sweet if a new ticket is created, it would send a request to a webhook saying there's a new ticket. This option is optional but available for anyone to use. Not sure if cp.gg would benefit from this though

### Additional context
N/A

**Comment by GeckoBoy84** [comment] 2022-08-14 18:39
Duplicate of #254

**Closed** 2022-08-14 18:40 UTC
