### ISSUE TITLE
[Feature] The new GoPay payment gateway

### ISSUE THREAD

**Issue by Mr-Rene** [ControlPanel-gg/dashboard#777] opened 2023-03-29 12:04 UTC
### Feature Description

> The only reason why the GoPay payment gateway should be added is that it is a Czech-Slovak payment gateway.
> This payment gateway will mainly help Czechs and Slovaks, since I myself am a Slovak, so I will be happy to use this payment gateway.
> Vysoký Vagon himself uses this payment gateway, and therefore I see no reason why it should not be added to the payment methods.

### Solution Idea

• This GoPay payment gateway should be implemented in the same way as e.g. PayPal, Stripe. And it should be implemented mainly, as I already mentioned, for the reason that it will be easier for us to work with the gateway that is used by more than 80% of guest hostings in the Czech Republic and Slovakia.

### Additional Info

• Link: https://www.gopay.com/en/integration/ here is the website where everything needed for implementation should be. Thanks in advance for reading and have a nice day.

**Comment by IceToast** [comment] 2023-03-29 12:17
Duplicate of #256

**Closed by IceToast** 2023-03-29 12:17 UTC
Labels: feature
