### ISSUE TITLE
Accept Crypto Payments

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#80] opened 2021-06-20 19:26 UTC
# 🚀 Feature Request

It would be very nice to be able to accept crypto payments. This could be done either by:
-Third part integration (I am aware of a supposedly good system by Coinbase and several others such as BitPay) 
or by 
-Generating wallets (on an as need basis for each user that requests one (and let us choose popular coins to accept)). They can send payments to said generated wallets which can then be merged to our main wallets either automatically (immediately or at threshold/after certain timeout) or manually. Rates could be set manually or by various market APIs.

While my personal preference would be the second method, any way to accept crypto would be huge

**Comment by LogischJo** [comment] 2021-06-20 19:31
Support the creation of own wallets would be quite hard.  (Would miss the intention of this project aswell)I guess that we should be able to add payment gateways like the Coinbase System. https://commerce.coinbase.com/ @AVMG20 You can assign me if you want

**Comment by snaildos** [comment] 2021-06-21 08:46
btcpay

**Comment by William071802** [comment] 2021-06-21 12:06
> btcpay

That's perfect. It's exactly what I wanted without all the hassle of having to build it. Will also be really nice for anyone not wanting to make an account with an exchange.

**Comment by snaildos** [comment] 2021-06-21 13:10
Glad to spread the word. :)

**Comment by RamonRobben** [comment] 2021-06-21 13:14
@William071802 I am not sure if you went to a different website than I did but btcpay requires the client to have an address because they are asked to send money to the provided address.

@William071802 @snaildos I don't think BTCPay is a very good processor. For a few reasons:

1. Your client will need a BTC wallet
2. Your client will need to pay BTC transaction fee's for any transaction (currently $5-$10)
3. I'm not sure if you can accept multiple currencies. I saw something but its weird to set up.

A better alternative would be BitPay highly professional company and crypto processor. But we would have to look into some more possible providers as I would like that clients don't have to pay blockchain transaction fees, don't need an exchange/wallet.

**Comment by snaildos** [comment] 2021-06-21 13:37
Also, there is alt coin support on btcpay.

**Comment by RamonRobben** [comment] 2021-06-21 13:55
@snaildos can you generate a demo for tron, dogecoin and ethereum and show it to me? I can only seem to generate a payment window for BTC

**Comment by snaildos** [comment] 2021-06-22 10:33
> @snaildos can you generate a demo for tron, dogecoin and ethereum and show it to me? I can only seem to generate a payment window for BTC

You are going to need to find a online demo.

**Comment by snaildos** [comment] 2021-06-22 10:35
Oops, accidently pressed sent. Ye, I mean, I can't set it up because of many differant problems and stuff. Idk, it's been a couple of years since I used this service. If your going to want that, you can find a online hosted versions and then request a coin by the owners contact

**Comment by William071802** [comment] 2021-06-22 19:16
> @William071802 I am not sure if you went to a different website than I did but btcpay requires the client to have an address because they are asked to send money to the provided address.
> 
> @William071802 @snaildos I don't think BTCPay is a very good processor. For a few reasons:
> 
> 1. Your client will need a BTC wallet
> 2. Your client will need to pay BTC transaction fee's for any transaction (currently $5-$10)
> 3. I'm not sure if you can accept multiple currencies. I saw something but its weird to set up.
> 
> A better alternative would be BitPay highly professional company and crypto processor. But we would have to look into some more possible providers as I would like that clients don't have to pay blockchain transaction fees, don't need an exchange/wallet.

I took a deeper look at BTCPay and here are my findings in relation to what you've mentioned
1. I don't see an issue with needing a BTC wallet to accept BTC
2. If I understood correctly they use the Lightening Network, which avoids those fees
3. It appears that they do via CoinSwitch integration (pretty easily I might add, it integrates into the checkout UI)

**Comment by GeckoBoy84** [comment] 2022-07-21 19:17
Duplicate of #411

**Closed by GeckoBoy84** 2022-07-21 19:17 UTC
Labels: feature, Low Priority
