### ISSUE TITLE
[feature] Announcement banners

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#511] opened 2022-08-10 00:57 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

No

### Describe the solution you'd like

There's no solution?

(Describe your proposed solution here.)

### Additional context

Add on the admin page to write announcements. (e.g if you're gonna have maintenance, you can announce that on your client page & it'll be on top of every page automatically). You could also customize it how you want. Like the verify your email warning box, but then announcements related.

(Write your answer here.)

**Comment by sybetjeh** [comment] 2022-08-10 00:58
#28 this is what I mean^. It's pretty much made over a year ago and it still hasn't been implemented. I'd love to see this feature on controlpanel.gg!

**Comment by 1day2die** [comment] 2022-08-10 06:16
dupe of #28 :P

**Closed by 1day2die** 2022-08-10 06:16 UTC
