### ISSUE TITLE
[feature] ticket system

### ISSUE THREAD

**Issue by loulou133** [ControlPanel-gg/dashboard#413] opened 2022-02-27 10:37 UTC
Hello, it would be nice if you make a ticket system on the panel. that would be great !!
Like PteroBilling 
![image](https://user-images.githubusercontent.com/72643424/155878953-12d40ab4-9100-4b10-aa98-aea0d861528c.png)

**Comment by 1day2die** [comment] 2022-02-28 11:22
hi,
please stick to the format provided.

also duplicate of https://github.com/ControlPanel-gg/dashboard/issues/176

**Closed by 1day2die** 2022-02-28 11:22 UTC
Labels: feature
