### ISSUE TITLE
[feature] more item type on the store 

### ISSUE THREAD

**Issue by aldigunawan-dev** [ControlPanel-gg/dashboard#471] opened 2022-07-02 17:02 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

I have same addon I sell on my hosting such as dynmap setup, dedicated IP, more port, etc
But I cannot put any other type of things in the store other than credits and server slots.

What about add third type of item that can be sell on the store
call it "Other" or something. And after purchase, clients can make tickets or contact support to claim the addon the bought

### Describe the solution you'd like

Add third item type on the store.

### Additional context

Call it "other" or even let the admin change the name to something else as they liked. Or maybe make so admin can add some kinds of custom type. Like category so they can add, change, or remove the type of item that they sell on their store. So they can have "addon", "services", or whatever they want

**Comment by GeckoBoy84** [comment] 2022-07-21 18:46
Duplicate of #381

**Closed** 2022-08-14 20:05 UTC
