### ISSUE TITLE
[feature] Misc option in store

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#679] opened 2023-01-31 08:01 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

Can only sell server slots and credits but not additional things.

### Describe the solution you'd like

Add a misc option for items on the store (Like credits and server slots) that doesnt need to do anything, just take payment and assign client role. Ability to add a custom description of what the product is

**Comment by 1day2die** [comment] 2023-01-31 09:07
Out of scope.
Duplicate of  https://github.com/ControlPanel-gg/dashboard/issues/381

**Closed by 1day2die** 2023-01-31 09:07 UTC

**Comment by GeckoBoy84** [comment] 2023-02-15 08:03
Not a duplicate - this is for including monthly credit charging.
