### ISSUE TITLE
[feature] Bill user for existing server

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#420] opened 2022-04-02 19:30 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I can't create server with custom specs on pterodactyl for the user and bill the user for it.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add way that you can link existing server to user in admin area. There should be field where you enter server id/UUID that you want to link and that you can set monthly credit price for it.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by GeckoBoy84** [comment] 2022-08-14 19:56
Duplicate of #170

**Closed by GeckoBoy84** 2022-08-14 19:56 UTC
Labels: feature

**Comment by anondev-sudo** [comment] 2022-08-15 04:57
Not really

**Comment by anondev-sudo** [comment] 2022-08-15 04:58
I mean that there should be link new server on the user's page where you set server id and price for it in credits so you can make custom plan server for users and bill them custom price
