### ISSUE TITLE
[Feature] Webhook Discord for Tickets

### ISSUE THREAD

**Issue by Shykuzo** [ControlPanel-gg/dashboard#732] opened 2023-02-10 13:10 UTC
### Feature Description

Be able to create a Webhook Discord that would send a message (Modifiable, if possible, via placeholders for example) in a channel in order to inform us when a ticket is created, closed or deleted with information such as the name of the ticket, the person who closed or deleted it, the person who created it, the category, the related service, ...

### Solution Idea

You could add a "Ticket" section in the settings to be able to configure the Webhook and other ticket-related options.

This would be very useful to know when a ticket is created without necessarily having to check the site H24.

**Comment by GeckoBoy84** [comment] 2023-02-10 16:03
You can purchase this addon on the market already.

**Comment by Shykuzo** [comment] 2023-02-10 16:20
> You can purchase this addon on the market already.

I was not aware of this add-on, however, it is not customizable as I suggested.

Also, it's another one of those damn paid add-ons, ControlPanel is 100% free but all the interesting add-ons are paid, it's horribly annoying.

**Comment by GeckoBoy84** [comment] 2023-02-10 16:22
The developers rely on donations/purchases to continue. Without them cp.gg would not be a free software.

**Comment by Shykuzo** [comment] 2023-02-10 16:25
> The developers rely on donations/purchases to continue. Without them cp.gg would not be a free software.

I know but why don't add-on developers do the same?
If ControlPanel is free, why shouldn't add-ons be free?

Especially since there are paid add-ons that add almost nothing, I know that creating an add-on is complicated but to charge for them when they add almost nothing is abusive.

Especially since the prices are almost systematically above 10€ ...

**Comment by 1day2die** [comment] 2023-02-11 10:03
> > The developers rely on donations/purchases to continue. Without them cp.gg would not be a free software.
> 
> I know but why don't add-on developers do the same?
> If ControlPanel is free, why shouldn't add-ons be free?
> 
> Especially since there are paid add-ons that add almost nothing, I know that creating an add-on is complicated but to charge for them when they add almost nothing is abusive.
> 
> Especially since the prices are almost systematically above 10€ ...

You are happily invitee to continue this discussion on our discord :)

**Comment by sybetjeh** [comment] 2023-02-11 11:16
whats that for logic? every oftware has paid extensions, this is just not an us thing. these addons are also not above 10 euro most of the time -> and these are optional, cpgg works fine without them.

**Comment by IceToast** [comment] 2023-02-11 13:32
_Im ignoring the discussion about addons free/paid._

This is a valid feature request that i would like to see implemented. 
We should consider adding webhook support in general, for other sections too (e.g. server creation, payments...).

**Comment by GeckoBoy84** [comment] 2023-02-11 13:33
Duplicate of #254

**Closed by GeckoBoy84** 2023-02-11 13:33 UTC
Labels: feature
