### ISSUE TITLE
[feature] Send email 3 days before servers are suspended

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#344] opened 2021-12-24 14:05 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Users don't check dashboard often and then their servers are suspended.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add that users will be reminded by email to purchase 3 days before their servers will be suspended.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Make it as config option for admins that they can change days before suspend reminder, when they set it to 0, it should be disabled.

**Comment by 1day2die** [comment] 2021-12-24 14:07
Duplicate of #255 which you also suggested

**Comment by anondev-sudo** [comment] 2021-12-24 14:08
When someone will look at it, you should also consider adding that notification that servers were suspended will be send just once - https://github.com/ControlPanel-gg/dashboard/issues/246

Also this reminder before suspension should be send once.

**Closed by 1day2die** 2021-12-24 14:07 UTC
Labels: enhancement
