### ISSUE TITLE
[feature] Automatic Server Deletetion 

### ISSUE THREAD

**Issue by Tix-Hosting** [ControlPanel-gg/dashboard#469] opened 2022-06-28 06:32 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

If you have many users and therefore many servers, you quickly lose track of which servers are just rotten. This takes away resources from the node. For this reason you have to manually delete inactive servers (servers that are not paid for and run out of credits for X time) after they have been suspended.

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

After a server is automatically suspended by the system due to insufficient credits, the server automatically goes into a grace period.  Whether you want this phase and how long it should last should be able to be specified in the settings.  After the end of the phase, the server should be irrevocably deleted.  A user should get an information when this phase starts and warnings (email, panel, API) in the phase based on the set time.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

I do not know if a Issue for that does already Exist, i looked over the Issues but did not found one :) (The iPad App is quite bad...)

**Comment by Tix-Hosting** [comment] 2022-06-28 06:34
just found out that this issue already exists in #224 ...

I am sorry about the Double Issue, i blame the iPad GitHub app for it xD

**Comment by GeckoBoy84** [comment] 2022-07-21 18:58
Duplicate of #224

**Closed by GeckoBoy84** 2022-07-21 18:58 UTC
