### ISSUE TITLE
[feature] Add option to be able to modify the resources of the server created 

### ISSUE THREAD

**Issue by NoHaxito** [ControlPanel-gg/dashboard#342] opened 2021-12-22 15:17 UTC
# 🚀 Feature Request
Add an option to modify the created server plan (plan only)

**Comment by snaildos** [comment] 2021-12-22 15:19
You mean upgrade/downgrade?

**Comment by IceToast** [comment] 2021-12-22 22:52
Duplicate of #74

**Comment by NoHaxito** [comment] 2021-12-23 01:17
> 

Yes

**Closed** 2021-12-23 18:41 UTC
Labels: enhancement
