### ISSUE TITLE
Register Account fails if Email is already Used on Pterodactyl

### ISSUE THREAD

**Issue by MrPvTDagger** [ControlPanel-gg/dashboard#274] opened 2021-11-07 23:26 UTC
**Describe the bug 🐛**
If a user attempt to register a new account with an email address that already linked to a existing account on the pterodactyl panel it will just redirect you to the login page and not create the account.

**To Reproduce**
1. Have a already existing account on pterodactyl 
2. Register a new account on controlpanel-gg with the same email on pterodactyl

**Expected behavior**
Could show a error that the account already exists and to contact administrator?

**Additional context**
I know this is a weird edge case where this can happens but I thought I would report it anyways

**Comment by j122j** [comment] 2021-11-08 00:01
This is not a bug, it should fail. But yes, an error could be shown.

**Comment by anondev-sudo** [comment] 2021-12-24 09:26
Also the same when Discord account is already linked to some dashboard account and you want to link it to different account error 500 is shown. It should show some error message that "This Discord account is already linked. You can contact support team."

**Comment by 1day2die** [comment] 2021-12-26 22:38
Fixed by https://github.com/ControlPanel-gg/dashboard/pull/347

**Closed** 2021-12-26 22:49 UTC
Labels: bug, In Progress
