### ISSUE TITLE
[feature] Choosing a location instead of node on costumer side.

### ISSUE THREAD

**Issue by Zoe8338** [ControlPanel-gg/dashboard#366] opened 2022-01-13 11:59 UTC
# 🚀 Feature Request

idk if this is already a thing, but when the costumer is buying a server, instead of choosing a node he could choose a Location and then the panel would see which has more resource available to deploy it. This way if u have multiple nodes in the same region they can be balanced.
and the admin when creating the server settings he could put which nodes it wants to be able for balancing
if that makes any sense

**Comment by Tix-Hosting** [comment] 2022-01-13 12:12
Your feature request is very similar to mine: https://github.com/ControlPanel-gg/dashboard/issues/286 

I think the idea that you can sort by country makes a lot of sense!  :) I hope that this will be implemented at some point :)
👍

**Comment by anondev-sudo** [comment] 2022-01-13 14:19
It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)

**Comment by Zoe8338** [comment] 2022-01-13 14:26
> It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)

@anondev-sudo That's what I mean with balancing yes. And is one of the reasons that I think choosing location over node is better.

**Comment by IceToast** [comment] 2022-01-13 15:31
> It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)

If you have setup ptero correctly, controllpanel cannot overallocate your Pterodactyl node!

**Comment by Zoe8338** [comment] 2022-01-13 15:34
> > It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)
> 
> If you have setup ptero correctly, controllpanel cannot overallocate your Pterodactyl node!

They mean it on this feature, not on the current panel.

**Comment by IceToast** [comment] 2022-01-13 16:18
> > > It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)
> > 
> > 
> > If you have setup ptero correctly, controllpanel cannot overallocate your Pterodactyl node!
> 
> They mean it on this feature, not on the current panel.

No, @anondev-sudo was talking about a "bug" that a user could setup a server on a node and overallocate it -> node does not have enough resources free.
If you setup pterodactyl correctly no user cannot install a server on it that would lead into overallocation of any resource.

**Comment by Zoe8338** [comment] 2022-01-13 16:19
> > > > It should auto choose node from the location that is not overallocated (it should not overallocate node as it does currently, users can go over the resource limit set on ptero)
> > > 
> > > 
> > > If you have setup ptero correctly, controllpanel cannot overallocate your Pterodactyl node!
> > 
> > 
> > They mean it on this feature, not on the current panel.
> 
> No, @anondev-sudo was talking about a "bug" that a user could setup a server on a node and overallocate it -> node does not have enough resources free. If you setup pterodactyl correctly no user cannot install a server on it that would lead into overallocation of any resource.

Oh I see

**Comment by anondev-sudo** [comment] 2022-01-13 20:19
Will user get error when their server would overallocate the node (go over the limit set on ptero)?

**Comment by 1day2die** [comment] 2022-01-14 09:21
pretty much dupe of this?
https://github.com/ControlPanel-gg/dashboard/issues/286

reopen if im incorrect

**Closed by 1day2die** 2022-01-14 09:21 UTC
Labels: enhancement
