### ISSUE TITLE
Implementation of support ticket system in dashboard

### ISSUE THREAD

**Issue by firinggamers** [ControlPanel-gg/dashboard#365] opened 2022-01-11 12:35 UTC
# 🚀 Feature Request

Implementation of support ticket system for enquiries etc for clients.

**Comment by anondev-sudo** [comment] 2022-01-13 14:20
Really good idea, and in the ticket creation form there should be select to choose which server is the ticket regarding of

**Comment by 1day2die** [comment] 2022-01-14 09:19
duplicate of
https://github.com/ControlPanel-gg/dashboard/issues/176

please use the provided format

**Closed by 1day2die** 2022-01-14 09:19 UTC
Labels: enhancement
