### ISSUE TITLE
[Feature] Sell additional non-server products in the store

### ISSUE THREAD

**Issue by thewilloftheshadow** [ControlPanel-gg/dashboard#171] opened 2021-08-13 15:52 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

There is no way to sell additional products like extra IP addresses or extra RAM. When we did our billing manually, we manually upped the individual servers, and we would be happy to continue this way, but there is no easy way to charge them for it.

### Describe the solution you'd like

Add a way to sell products in the store that aren't specifically servers. Then, later on, you could add the ability to sell upgrades to servers in the store.

**Comment by anondev-sudo** [comment] 2021-08-13 19:04
I have suggested that https://github.com/ControlPanel-gg/dashboard/issues/34

**Comment by thewilloftheshadow** [comment] 2021-08-13 20:25
That issue is about specifically adding resources to the servers. I am just wanting a way to sell non-server items though the billing on ControlPanel.gg

**Comment by RamonRobben** [comment] 2021-08-13 20:31
@thewilloftheshadow the whole dashboard is specifically made to sell servers and bill them. What other non-server items are you selling?

**Comment by LogischJo** [comment] 2021-08-13 20:42
> @thewilloftheshadow the whole dashboard is specifically made to sell servers and bill them. What other non-server items are you selling?

Much hosts sell services, like additional support with plugins (for mc) etc. Would be pretty cool to have something like that.

**Comment by RamonRobben** [comment] 2021-08-13 23:46
@LogischJo Ah now I understand what the issue is. The problem with this is that the system is currently built on a very specific way of billing which is billing per package per server.

What you can do is make a seperate page, write php code to allow admins to add services that users can switch on/off or purchase once, and then write your own billing code or reuse some code from the server billing.

Theoretically possible, Not really sure if this is the scope of the project because you can also have users create a ticket and then send them a paypal pay link and do it manually. It's also quite a lot of work.

**Comment by anondev-sudo** [comment] 2021-08-14 08:36
It will be good if this will be added, as some users want extra ports, backups, ram, cpu or storage and it will be chaotic if we will create a lot of plans with this. There should be function to add something extra to the server (more ports or backups, ...). In admin area there should be added add-ons where admins can setup which add-ons they offer. And when creating server add option to choose add-ons. Add-ons should be added when option to upgrade existing server will be added

**Comment by AVMG20** [comment] 2021-08-14 13:13
> It will be good if this will be added, as some users want extra ports, backups, ram, cpu or storage and it will be chaotic if we will create a lot of plans with this. There should be function to add something extra to the server (more ports or backups, ...). In admin area there should be added add-ons where admins can setup which add-ons they offer. And when creating server add option to choose add-ons. Add-ons should be added when option to upgrade existing server will be added

How is this *non-server* related?

**Comment by AVMG20** [comment] 2021-08-14 13:15
We currently want to add ways to link products to eggs, afterwards we may look into an addon system. That allows ppl to purchase **addons** for their servers and that will be billed on top of the server price. I believe this is something you want? Addons would be more ports , r , cpu , etc....

**Comment by anondev-sudo** [comment] 2021-08-14 14:38
Yes, I mean this. Sorry for bad explanation.

**Comment by somerandomcloud** [comment] 2021-08-14 14:48
> We currently want to add ways to link products to eggs, afterwards we may look into an addon system. That allows ppl to purchase **addons** for their servers and that will be billed on top of the server price. I believe this is something you want? Addons would be more ports , r , cpu , etc....

Yeah, pretty sure this is something that ALOT of users want... This should be somewhat prioritized imo, just to make these things easier

**Comment by anondev-sudo** [comment] 2021-08-14 15:52
Users should be able to choose add-ons also when creating server and apply them to existing server

**Comment by GeckoBoy84** [comment] 2022-07-21 18:48
Duplicate of #381  and #239

**Comment by GeckoBoy84** [comment] 2022-07-21 18:48
Duplicate of https://github.com/ControlPanel-gg/dashboard/issues/381 and https://github.com/ControlPanel-gg/dashboard/issues/239

**Closed by GeckoBoy84** 2022-07-21 18:48 UTC
Labels: feature
