### ISSUE TITLE
[feature] Server Syncing

### ISSUE THREAD

**Issue by snaildos** [ControlPanel-gg/dashboard#493] opened 2022-07-20 09:17 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

A syncing button. An option to sync one server, or multiple, or all in controlpanel.gg to sync pterodactyl with the new resources on the updated product as well as a way to update credits the product is using after pressing sync.

### Example

quoted a customer 2 months ago, now we both agreed that he is paying not enough
want to change it but I cant without editing server ID, deleting, remaking, deleting remade server on ptero, change server ID again

**Comment by GeckoBoy84** [comment] 2022-07-21 18:56
Duplicate of #170

**Closed by GeckoBoy84** 2022-07-21 18:56 UTC
